// ===========================================================================
// Generate the service catalogue from the manifest snapshot.
//
//   node scripts/generate.mjs           # write
//   node scripts/generate.mjs --check   # fail if the committed output differs
//
// One descriptor per declared function. Everything downstream — the runtime
// validator, the TypeScript types, the docs, the LLM tool definitions — is
// derived from these descriptors, so the manifest stops being documentation
// and becomes the thing that decides whether a call is allowed.
// ===========================================================================
import { readFileSync, writeFileSync } from 'node:fs';
import {
  POSTMESSAGE_BOUND, LOCAL, SERVER_TOOLS, SERVER_ONLY_TOOLS, mutates, defaultCache,
} from './bindings.js';
import {
  VALUGURU_CHANNEL, APP_STATE_CHANNEL, RETURNS, SERVER_ONLY_RECONCILIATION, KNOWN_DELTAS,
  REQUIREMENTS,
} from './functions.js';
import {
  API_POINTER_MODULES, API_POINTER_FUNCTIONS, DUPLICATE_DECLARATIONS, pointerSummary,
} from './apiPointers.js';
// The registry the SDK actually loads. Importing it is what lets the parity
// matrix report implementation status instead of asserting it.
import { serviceRegistry } from '../src/services/registry.js';
import '../src/services/impl/index.js';

const root = new URL('../', import.meta.url);
const check = process.argv.includes('--check');

const snapshot = JSON.parse(
  readFileSync(new URL('manifests/service-manifests.snapshot.json', root), 'utf8'),
);

const postMessageBound = new Set(POSTMESSAGE_BOUND);
const local = new Set(LOCAL);
const serverTools = new Set(SERVER_TOOLS);
const valuguru = new Set(VALUGURU_CHANNEL);
const appStateChannel = new Set(APP_STATE_CHANNEL);

/**
 * WHICH socket (or none) serves a declared function. `binding` says the kind
 * of thing that answers; `channel` says the thing itself — the distinction
 * Phase 2 had to make before a handler could be written (scripts/functions.js).
 */
function channelFor(key, binding) {
  if (binding !== 'socket') return binding;
  if (valuguru.has(key)) return 'valuguru';
  if (appStateChannel.has(key)) return 'app-state';
  return 'roomful';
}

const snake = (action) => action.replace(/-/g, '_');
const camel = (action) => action.replace(/[-_](\w)/g, (_, c) => c.toUpperCase());

const descriptors = [];
for (const service of snapshot.services) {
  for (const intent of service.intents) {
    const key = `${service.id}.${intent.action}`;
    const binding = postMessageBound.has(key) ? 'postmessage' : local.has(key) ? 'local' : 'socket';
    const channel = channelFor(key, binding);
    const isMutation = mutates(key, intent.action);
    descriptors.push({
      key,
      service: service.id,
      action: intent.action,
      fn: snake(intent.action),
      method: camel(intent.action),
      toolName: `service__${service.id}__${snake(intent.action)}`,
      serviceTitle: service.title,
      serviceDescription: service.description,
      source: service.source,
      description: intent.description,
      availability: intent.availability,
      permissions: intent.permissions,
      // No manifest intent declares permissions today, so the scope a caller
      // needs is derived: one read scope and one write scope per service.
      scopes: [`${service.id.toLowerCase()}:${isMutation ? 'write' : 'read'}`],
      binding,
      mutates: isMutation,
      cache: defaultCache(key, binding, isMutation, intent.params, channel),
      channel,
      returns: RETURNS[key] ?? { type: 'unknown', description: '' },
      params: intent.params,
      implementedBy: serverTools.has(key) ? `service__${service.id}__${snake(intent.action)}` : null,
    });
  }
}

descriptors.sort((a, b) => a.key.localeCompare(b.key));

// --- src/services/catalog.generated.js -------------------------------------
const banner = `// GENERATED by scripts/generate.mjs from manifests/service-manifests.snapshot.json.
// Do not edit by hand: run \`npm run build\`. The decisions that are not in the
// manifest (socket/local/postmessage, mutates, cache) come from scripts/bindings.js.
`;

const catalogJs = `${banner}
/** @typedef {import('./descriptors.js').ServiceDescriptor} ServiceDescriptor */

/** @type {ServiceDescriptor[]} */
export const SERVICE_DESCRIPTORS = ${JSON.stringify(descriptors, null, 2)};

/** Server tools that implement no declared intent. */
export const SERVER_ONLY_TOOLS = ${JSON.stringify(SERVER_ONLY_TOOLS, null, 2)};

/** Phase 2b — what happens to each of them, and why (scripts/functions.js). */
export const SERVER_ONLY_RECONCILIATION = ${JSON.stringify(SERVER_ONLY_RECONCILIATION, null, 2)};
`;

// --- types/valu-services.d.ts ----------------------------------------------
const tsType = (type) => ({
  string: 'string', number: 'number', boolean: 'boolean', object: 'Record<string, any>',
  array: 'any[]', 'string[]': 'string[]', 'object[]': 'Record<string, any>[]',
  FileList: 'FileList',
}[type] ?? 'any');

const paramType = (param) =>
  param.options ? param.options.map((o) => JSON.stringify(o)).join(' | ') : tsType(param.type);

const jsdoc = (indent, lines) =>
  `${indent}/**\n${lines.filter(Boolean).map((l) => `${indent} * ${l}`).join('\n')}\n${indent} */`;

const byService = new Map();
for (const d of descriptors) {
  if (!byService.has(d.service)) byService.set(d.service, []);
  byService.get(d.service).push(d);
}

let dts = `${banner}
// Typed surface of every declared Valu service function.

// The package's hand-written declarations are an AMBIENT module, so this
// names the package rather than the file: both are in the same program
// (\`npm run typecheck\`), and a relative import of an ambient module does not
// resolve.
import type { ValuAck } from '@arkeytyp/valu-api';

export type ServiceBinding = 'socket' | 'local' | 'postmessage';
export type IntentAvailability = 'ai' | 'developer';

`;

/** The declared return shape, as TypeScript. `object` is an open record. */
const returnType = (returns) => (returns?.type && returns.type !== 'unknown'
  ? returns.type.replace(/\bobject\b/g, 'Record<string, any>')
  : 'any');

const resultName = (d) => `${d.service}${d.method[0].toUpperCase()}${d.method.slice(1)}Result`;

for (const [service, fns] of byService) {
  for (const d of fns) {
    const all = [...d.params.required.map((p) => [p, true]), ...d.params.optional.map((p) => [p, false])];
    dts += `${jsdoc('', [`${d.key} — ${d.returns.description || d.description}`])}\n`;
    dts += `export type ${resultName(d)} = ${returnType(d.returns)};\n\n`;
    dts += `${jsdoc('', [`${d.key} — ${d.description}`])}\n`;
    dts += `export interface ${service}${d.method[0].toUpperCase()}${d.method.slice(1)}Params {\n`;
    for (const [p, required] of all) {
      dts += `${jsdoc('  ', [p.description])}\n`;
      dts += `  ${p.name}${required ? '' : '?'}: ${paramType(p)};\n`;
    }
    dts += `}\n\n`;
  }
}

dts += `/** Every service, with each declared function as a method. */\nexport interface ValuServices {\n`;
for (const [service, fns] of byService) {
  dts += `${jsdoc('  ', [fns[0].serviceDescription])}\n  ${service}: {\n`;
  for (const d of fns) {
    const hasParams = d.params.required.length + d.params.optional.length > 0;
    const required = d.params.required.length > 0;
    const paramsName = `${service}${d.method[0].toUpperCase()}${d.method.slice(1)}Params`;
    dts += `${jsdoc('    ', [d.description, `@binding ${d.binding}`, `@channel ${d.channel}`, `@scope ${d.scopes.join(' ')}`])}\n`;
    dts += `    ${d.method}(${hasParams ? `params${required ? '' : '?'}: ${paramsName}` : ''}): Promise<ValuAck<${resultName(d)}>>;\n`;
  }
  dts += `  };\n`;
}
dts += `}\n\nexport type ServiceName = keyof ValuServices;\n`;

// --- docs/services.md ------------------------------------------------------
const counts = descriptors.reduce((acc, d) => ({ ...acc, [d.binding]: (acc[d.binding] ?? 0) + 1 }), {});
let md = `<!-- GENERATED by scripts/generate.mjs. Do not edit: run \`npm run build\`. -->
# Valu service reference

Every function the app declares in \`SERVICE_MANIFESTS\`, with the binding that
serves it and the scope a caller needs.

| binding | count | meaning |
|---|---|---|
| \`socket\` | ${counts.socket} | answered over the Valu socket |
| \`local\` | ${counts.local} | answered by the SDK itself |
| \`postmessage\` | ${counts.postmessage} | UI-bound — the Valu Social application answers it over the postMessage bridge |
| **total** | **${descriptors.length}** | |

${SERVER_ONLY_TOOLS.length} server tools implement no declared intent and are not in this
table: ${SERVER_ONLY_TOOLS.map((t) => `\`${t}\``).join(', ')}.

`;

for (const [service, fns] of byService) {
  md += `## ${service}\n\n${fns[0].serviceDescription}\n\nSource: \`${fns[0].source}\`\n\n`;
  for (const d of fns) {
    md += `### \`${d.key}\`\n\n${d.description}\n\n`;
    md += `- binding: \`${d.binding}\` · channel: \`${d.channel}\`${d.implementedBy ? ` · server tool: \`${d.implementedBy}\`` : ''}\n`;
    md += `- returns: \`${d.returns.type}\`${d.returns.description ? ` — ${d.returns.description}` : ''}\n`;
    md += `- scope: \`${d.scopes.join('`, `')}\` · ${d.mutates ? 'mutates state' : 'read-only'}\n`;
    md += `- cache: \`${d.cache.mode}\`${d.cache.mode !== 'none' ? ` (ttl ${d.cache.ttlMs}ms, key \`${d.cache.key ?? 'service'}\`)` : ''}\n`;
    md += `- availability: ${d.availability.length ? d.availability.map((a) => `\`${a}\``).join(', ') : '_none_'}\n\n`;
    const all = [...d.params.required.map((p) => [p, true]), ...d.params.optional.map((p) => [p, false])];
    if (all.length) {
      md += `| param | type | required | description |\n|---|---|---|---|\n`;
      for (const [p, required] of all) {
        const type = p.options ? p.options.map((o) => `\`${o}\``).join(' \\| ') : `\`${p.type}\``;
        md += `| \`${p.name}\` | ${type} | ${required ? 'yes' : 'no'} | ${p.description.replace(/\|/g, '\\|')} |\n`;
      }
      md += `\n`;
    } else {
      md += `Takes no parameters.\n\n`;
    }
  }
}

// --- docs/parity.md + docs/parity-matrix.csv --------------------------------
// THE PARITY MATRIX, generated rather than maintained. The plan shipped it as
// a spreadsheet; a spreadsheet cannot notice that a function was implemented,
// so this is built from the catalogue AND from the registry — `npm run
// check:generated` fails when the two drift, which is the only way a parity
// table stays true after the week it was written.
const implemented = new Set(serviceRegistry.implemented());

const STATUS = (d) => {
  if (d.binding === 'postmessage') return 'frame command';
  return implemented.has(d.key) ? 'implemented' : 'declared only';
};

const byChannel = descriptors.reduce((acc, d) => ({ ...acc, [d.channel]: (acc[d.channel] ?? 0) + 1 }), {});
const implementedCount = descriptors.filter((d) => implemented.has(d.key)).length;

let parity = `<!-- GENERATED by scripts/generate.mjs. Do not edit: run \`npm run build\`. -->
# Parity matrix

Every declared function, what serves it, and whether this package implements
it. Generated from the catalogue and from the registry the SDK actually loads,
so a function listed \`implemented\` here has a handler — the two cannot drift
without \`npm run check:generated\` failing.

| | count |
|---|---|
| declared service intents | **${descriptors.length}** |
| SDK-able (socket + local) | **${descriptors.length - counts.postmessage}** |
| implemented in this package | **${implementedCount}** |
| frame commands (postMessage-bound) | **${counts.postmessage}** |
| server tools with no declared intent | **${SERVER_ONLY_TOOLS.length}** |

## Channels

\`binding\` says the KIND of thing that answers; \`channel\` says which one.
Phase 2 added the second column: "socket" turned out to be three different
things, and a function written for the wrong one fails in a way the ack
envelope cannot explain.

| channel | count | what serves it |
|---|---|---|
| \`roomful\` | ${byChannel.roomful ?? 0} | the Roomful platform socket — \`ValuSocket.emit(ns, payload)\` |
| \`valuguru\` | ${byChannel.valuguru ?? 0} | the Valu Guru server's \`data_request\` channel — \`valuguru.*\` ops |
| \`app-state\` | ${byChannel['app-state'] ?? 0} | no RPC exists; the answer is in the Valu Social application's own memory |
| \`local\` | ${byChannel.local ?? 0} | computed by the SDK |
| \`postmessage\` | ${byChannel.postmessage ?? 0} | the postMessage bridge (\`src/frame/FrameCommands.js\`) |

## Functions

| service | function | binding | channel | mutates | cache | server tool | status |
|---|---|---|---|---|---|---|---|
`;
for (const d of descriptors) {
  parity += `| ${d.service} | \`${d.action}\` | ${d.binding} | \`${d.channel}\` | ${d.mutates ? 'write' : 'read'} `
    + `| \`${d.cache.mode}\` | ${d.implementedBy ? `\`${d.implementedBy}\`` : '—'} | ${STATUS(d)} |\n`;
}

parity += `
## Server-only tools — the Phase 2b decisions

${SERVER_ONLY_TOOLS.length} tools in valu-guru-server implement no declared intent. Each one is
resolved below rather than left as a gap.

`;
for (const entry of SERVER_ONLY_RECONCILIATION) {
  parity += `### \`${entry.tool}\` — ${entry.disposition}\n\n${entry.decision}\n\n`;
  if (entry.declared.length) {
    parity += `Declared equivalent: ${entry.declared.map((k) => `\`${k}\``).join(', ')}.\n\n`;
  }
}

parity += `## Known behaviour deltas

Parity is not identical behaviour. These are the places this package knowingly
differs from the app, each one a decision rather than an oversight.

`;
for (const entry of KNOWN_DELTAS) {
  parity += `### \`${entry.key}\`\n\n${entry.delta}\n\n`;
}

// The same table as data, for anything that would rather diff than read.
let csv = 'service,function,binding,channel,mutates,cache,scopes,server_tool,status,returns\n';
for (const d of descriptors) {
  const cell = (v) => `"${String(v).replace(/"/g, '""')}"`;
  csv += [
    d.service, d.action, d.binding, d.channel, d.mutates ? 'write' : 'read', d.cache.mode,
    d.scopes.join(' '), d.implementedBy ?? '', STATUS(d), d.returns.type,
  ].map(cell).join(',') + '\n';
}

// --- docs/server-functions.md ----------------------------------------------
// THE SERVER-SIDE REFERENCE: what this package answers itself, for somebody
// wiring it into a runtime that is not a browser frame. docs/services.md lists
// what the platform DECLARES; this lists what the package SERVES, and what the
// runtime has to hand it before a call can succeed.
const served = descriptors.filter((d) => d.binding !== 'postmessage' && implemented.has(d.key));
const frame = descriptors.filter((d) => d.binding === 'postmessage');
const servedByService = new Map();
for (const d of served) {
  if (!servedByService.has(d.service)) servedByService.set(d.service, []);
  servedByService.get(d.service).push(d);
}

/**
 * Frame command → the method that runs it, read out of FrameCommands itself.
 *
 * NOT derived from the action name: five of the fifteen are deliberately named
 * for what they do rather than what the intent is called (`AiGuru.open` is
 * `openApplication`, `Application.close-application` is `closeSelf`), and a
 * table that camel-cased the action would send a reader to a method that does
 * not exist.
 */
const frameMethods = (() => {
  const src = readFileSync(new URL('src/frame/FrameCommands.js', root), 'utf8');
  const methods = new Map();
  let current = null;
  for (const line of src.split('\n')) {
    const declaration = /^\s{2}([a-zA-Z][\w]*)\s*\(/.exec(line);
    if (declaration) current = declaration[1];
    const run = /this\.run\('([^']+)'/.exec(line);
    if (run && current) methods.set(run[1], current);
  }
  return methods;
})();

for (const d of frame) {
  if (!frameMethods.has(d.key)) {
    throw new Error(`${d.key} is postMessage-bound but no FrameCommands method runs it`);
  }
}

/** The runtime requirements of a function: its channel, plus anything extra. */
const requirementsOf = (d) => {
  const channelReq = {
    roomful: '`socket`',
    valuguru: '`guru`',
    'app-state': null,
    local: null,
  }[d.channel];
  const extra = (REQUIREMENTS[d.key] ?? []).map((r) => `\`${r}\``);
  return [channelReq, ...extra].filter(Boolean).join(', ') || '—';
};

const signature = (d) => {
  const all = [
    ...d.params.required.map((p) => p.name),
    ...d.params.optional.map((p) => `${p.name}?`),
  ];
  return all.length ? `{${all.join(', ')}}` : '—';
};

const channelCounts = served.reduce((acc, d) => ({ ...acc, [d.channel]: (acc[d.channel] ?? 0) + 1 }), {});

let serverMd = `<!-- GENERATED by scripts/generate.mjs. Do not edit: run \`npm run build\`. -->
# Server functions

The ${served.length} functions **this package answers itself** — over a socket, or
locally — and what a runtime has to give it before each one can succeed.

This is the reference for embedding the SDK in something that is not a browser
frame: a Node service, an agent runtime, a test harness. For the platform's own
declaration of every intent (including the ${frame.length} that only a frame can serve)
read [services.md](services.md); for who implements what today read
[parity.md](parity.md).

Generated from the catalogue and from the registry the SDK actually loads: a
function listed here has a handler, and its requirements are asserted against
that handler by \`test/server-functions.test.js\`.

## Calling one

\`\`\`javascript
import { ServiceClient } from '@arkeytyp/valu-api/src/services/ServiceClient.js';
import { SocketTransport } from '@arkeytyp/valu-api/src/transport/SocketTransport.js';
import { NodeSocketAdapter } from '@arkeytyp/valu-api/src/socket/NodeSocketAdapter.js';

const client = new ServiceClient({
  transport: new SocketTransport({
    socket: new NodeSocketAdapter({ connection }), // the Roomful socket
    guru,                                          // the Valu Guru socket
    appState,                                      // state only the app holds
    applicationId: 'my-app',                       // WHO is calling
    config: { webBase, apiGate },                  // origins for URL builders
    fetchImpl: fetch,
  }),
});

const ack = await client.call('Users.get', { userId });   // { data } | { error }
const user = await client.invoke('Users.get', { userId }); // throws on error
\`\`\`

A function resolves by any name the platform already writes — \`Users.get\`,
\`Users.get_user\`, \`Users.getUser\`, \`service__Users__get\`.

## What a runtime must supply

| requirement | what it is | what happens without it |
|---|---|---|
| \`socket\` | a [\`ValuSocket\`](../src/socket/ValuSocket.js) — \`NodeSocketAdapter\` over a \`RoomfulConnectionManager\`, or \`BrowserSocketAdapter\` over the app's WebSocket service | \`SocketTransport\` refuses to construct |
| \`guru\` | a [\`ValuGuruSocket\`](../src/socket/ValuGuruSocket.js) — the Valu Guru server's \`data_request\` channel | the ${channelCounts.valuguru ?? 0} \`valuguru\` functions answer 503 **by name**, before the handler runs |
| \`appState\` | an [\`AppState\`](../src/app-state/AppState.js): state no RPC can produce, held by the Valu Social application or by your own runtime | the function answers 501 naming the capability it wanted |
| \`applicationId\` | WHICH application is calling, stamped by the runtime and never read from a caller's params | the functions scoped to an app answer 403 |
| \`config\` | \`{ webBase, apiGate }\` — the origins a resource URL is built on | defaults are used; a share link may point at the wrong deployment |
| \`fetch\` | outbound HTTP, for the local HTTP functions and the upload pipeline's bucket PUT | \`globalThis.fetch\`, if the runtime has one |

By channel: ${Object.entries(channelCounts).sort().map(([c, n]) => `${n} \`${c}\``).join(' · ')}.

## Errors

Every function resolves an ack — \`{data}\` or \`{error}\` — and never throws;
\`invoke\` is the throwing wrapper. The codes a caller must handle are in
[callbacks-policy.md](callbacks-policy.md); the ones specific to a missing
runtime piece are 503 (no such channel), 501 (no app-state capability, or a function
the transport cannot serve) and 403 (no application identity).

`;

for (const [service, fns] of servedByService) {
  serverMd += `## ${service}\n\n${fns[0].serviceDescription}\n\n`;
  serverMd += `| function | params | returns | mode | requires | cache |\n|---|---|---|---|---|---|\n`;
  for (const d of fns) {
    serverMd += `| \`${d.key}\` | ${signature(d)} | \`${d.returns.type}\` `
      + `| ${d.mutates ? 'write' : 'read'} | ${requirementsOf(d)} | \`${d.cache.mode}\` |\n`;
  }
  serverMd += `\n`;
  for (const d of fns) {
    // A `void` function's declared return reads as a statement of fact ("The
    // resource was deleted."); everything else names a value, so it reads as
    // the answer to the call.
    const answers = !d.returns.description ? ''
      : d.returns.type === 'void' ? ` ${d.returns.description}`
        : ` Answers ${d.returns.description.charAt(0).toLowerCase()}${d.returns.description.slice(1)}`;
    serverMd += `- \`${d.action}\` — ${d.description}${answers}\n`;
  }
  serverMd += `\n`;
}

serverMd += `## Not served here

${frame.length} declared intents are UI-bound: a picker that renders, a dock that
opens, a log buffer only the frame holds. A socket answers all ${frame.length} with the
same 501, and [\`src/frame/FrameCommands.js\`](../src/frame/FrameCommands.js)
gives them a named API over the postMessage bridge instead.

| intent | frame method |
|---|---|
`;
for (const d of frame) {
  serverMd += `| \`${d.key}\` | \`frame.${frameMethods.get(d.key)}()\` |\n`;
}

serverMd += `
${SERVER_ONLY_TOOLS.length} tools in valu-guru-server implement no declared intent and are not
functions of this package. [parity.md](parity.md) records the decision for each
one: ${SERVER_ONLY_TOOLS.map((t) => `\`${t}\``).join(', ')}.
`;

// --- docs/socket-functions.md ----------------------------------------------
// THE SOCKET SURFACE, as a list of features rather than a list of
// requirements. server-functions.md answers "what must my runtime supply";
// this one answers "what can I actually do over a socket, and which socket",
// which is the question somebody asks when `binding` in the catalogue has
// stopped making sense (docs/postmessage-vs-socket.md).
const onSocket = descriptors.filter(
  (d) => (d.channel === 'roomful' || d.channel === 'valuguru') && implemented.has(d.key),
);
const appStateFns = descriptors.filter((d) => d.channel === 'app-state');
const localFns = descriptors.filter((d) => d.channel === 'local');

const SOCKET_LABEL = { roomful: 'Roomful', valuguru: 'Valu Guru' };

/** `{roomId, networkId?}` — the call's shape at a glance. */
const paramList = (d) => {
  const all = [
    ...d.params.required.map((p) => p.name),
    ...d.params.optional.map((p) => `${p.name}?`),
  ];
  return all.length ? `\`{${all.join(', ')}}\`` : '`()`';
};

/** What the cache does to this function, in the words a caller cares about. */
const cacheNote = (d) => {
  const { mode, ttlMs } = d.cache;
  if (mode === 'read-through') return `cached ${Math.round((ttlMs ?? 0) / 1000)}s`;
  if (mode === 'seeded') return 'cache seeded by push';
  if (d.mutates) return 'invalidates the cache';
  return 'not cached';
};

/**
 * What this function needs BEYOND its socket, if anything.
 *
 * `VerusWallet.transfer` is the reason this is here: it emits on the Roomful
 * socket, so it is listed under one, but it cannot start without the wallet
 * identity only the application's own state can resolve. A socket-only reader would not guess
 * that. The tags are the same metadata server-functions.md renders, and
 * test/server-functions.test.js sweeps them against the handlers.
 */
const alsoNeeds = (d) => {
  const extra = (REQUIREMENTS[d.key] ?? []).filter((r) => r !== 'fetch' || d.channel !== 'local');
  if (!extra.length) return '';
  const label = (r) => (r.endsWith('?') ? `\`${r.slice(0, -1)}\` (optional)` : `\`${r}\``);
  return ` **also needs ${extra.map(label).join(', ')}.**`;
};

/** One bullet: the function, its shape, and the feature it provides. */
const featureLine = (d) => {
  const answers = !d.returns.description ? ''
    : d.returns.type === 'void' ? ` ${d.returns.description}`
      : ` Answers ${d.returns.description.charAt(0).toLowerCase()}${d.returns.description.slice(1)}`;
  return `- **\`${d.key}\`** ${paramList(d)} → \`${d.returns.type}\`\n`
    + `  ${d.description}${answers}${alsoNeeds(d)} *(${cacheNote(d)}; scope \`${d.scopes.join(' ')}\`)*\n`;
};

const socketByService = new Map();
for (const d of onSocket) {
  if (!socketByService.has(d.service)) socketByService.set(d.service, []);
  socketByService.get(d.service).push(d);
}

let socketMd = `<!-- GENERATED by scripts/generate.mjs. Do not edit: run \`npm run build\`. -->
# Socket functions

The ${onSocket.length} functions this package answers **over a socket** — a connection it
holds to a server and speaks itself — and the feature each one provides.

${onSocket.filter((d) => d.channel === 'roomful').length} of them run on the **Roomful socket** and ${onSocket.filter((d) => d.channel === 'valuguru').length} on the **Valu Guru
socket**. Neither one needs the Valu Social application: a Node service with a
connection can call all ${onSocket.length}. That is the whole difference from a
*postMessage-bound* function, which only the Valu Social application embedding
your iframe can serve — [postmessage-vs-socket.md](postmessage-vs-socket.md) is
that distinction in full.

Where to read what:

| doc | question it answers |
|---|---|
| [services.md](services.md) | what does the platform declare? (all ${descriptors.length} intents, every param) |
| [server-functions.md](server-functions.md) | what must my runtime supply before a call works? |
| **this file** | what can I do over a socket, and which socket does it? |
| [postmessage-vs-socket.md](postmessage-vs-socket.md) | what do \`postmessage\` and \`socket\` mean here? |
| [api-pointers.md](api-pointers.md) | the older generic mechanism, and what still needs it |

## The two sockets

| socket | functions | what it is | how you supply it | without it |
|---|---|---|---|---|
| Roomful | ${onSocket.filter((d) => d.channel === 'roomful').length} | the platform's own WebSocket — every RPC the app's services already use | \`new SocketTransport({ socket })\` | \`SocketTransport\` refuses to construct |
| Valu Guru | ${onSocket.filter((d) => d.channel === 'valuguru').length} | the Valu Guru server's \`data_request\` channel — a different server, envelope and auth | \`new SocketTransport({ socket, guru })\` | those ${onSocket.filter((d) => d.channel === 'valuguru').length} answer 503 **by name**, before the handler runs |

Both are the same contract to a handler
([\`ValuSocket\`](../src/socket/ValuSocket.js)), and both come in a browser and
a headless flavour, so a function written once runs in either runtime. What the
socket carries is the platform's own RPC, unchanged: \`Users.get\` emits
\`social:getUsersSimpleInfo\`, \`Rooms.get-permissions\` emits
\`room:permissions\` — the same messages the Valu Social app emits for the same
data.

## ${appStateFns.length} functions the catalogue calls socket-bound that are not on a socket

The most confusing row in the matrix, so it is worth being explicit. These are
declared like any other service intent and \`binding\` says \`socket\`, because
that is what the manifest implies. There is no RPC: the answer is in the **Valu
Social application's own memory**. \`channel\` says \`app-state\`, and a runtime
that holds the state passes it in as \`{ appState }\`; one that does not gets an
ack naming the capability it wanted.

| function | the state it reads | \`appState\` capability |
|---|---|---|
| \`AiGuru.get-chat-history\` | the session's in-memory message list | \`getChatHistory\` |
| \`AiGuru.get-agent-history\` | an agent's in-memory message list | \`getAgentHistory\` |
| \`Developer.list-applications\` | the Developer Portal's application list | \`listDeveloperApplications\` |
| \`Developer.create-application\` | the same store, plus the app registry | \`createDeveloperApplication\` |
| \`VerusWallet.get-balance\` | the balance the store cached off a push | \`getAgentWallet\` |

## ${localFns.length} functions with no socket at all

Answered inside the SDK from configuration, the clock or \`fetch\`:
${localFns.map((d) => `\`${d.key}\``).join(', ')}. They need no connection and
no bridge, and they are in [server-functions.md](server-functions.md) with the
rest of what a runtime must supply.

## The features, by service

Read functions first, then writes — the split matters, because a write bypasses
the cache on the way out and invalidates it on the way back, **including when
it fails** (a timed-out write may still have landed).

A few of them want something past the socket — an \`applicationId\` the runtime
stamps, a \`config\` origin, a \`fetch\`, or a piece of \`appState\`. Those say so
in bold, because without it the call answers 403 or 501 rather than working
partially. [server-functions.md](server-functions.md) is the same information
organized around a runtime rather than a feature.

`;

for (const [service, fns] of [...socketByService].sort()) {
  const sockets = [...new Set(fns.map((d) => SOCKET_LABEL[d.channel]))].join(' + ');
  socketMd += `### ${service} · ${fns.length} function${fns.length === 1 ? '' : 's'} · ${sockets} socket\n\n`;
  socketMd += `${fns[0].serviceDescription}\n\n`;
  // A service description describes the WHOLE service, so a reader of a
  // socket-only list needs to be told where the rest of it went — otherwise
  // AiGuru reads as "manages applications" above a single RAG query.
  const elsewhere = descriptors.filter((d) => d.service === service && !fns.includes(d));
  if (elsewhere.length) {
    const where = { postmessage: 'frame commands', 'app-state': 'application state', local: 'local to the SDK' };
    const groups = [...new Set(elsewhere.map((d) => d.channel))]
      .map((c) => `${elsewhere.filter((d) => d.channel === c).length} ${where[c]}`);
    socketMd += `*${elsewhere.length} more \`${service}\` intent${elsewhere.length === 1 ? ' is' : 's are'} `
      + `not on a socket: ${groups.join(', ')}.*\n\n`;
  }
  const reads = fns.filter((d) => !d.mutates);
  const writes = fns.filter((d) => d.mutates);
  if (reads.length) {
    socketMd += `**Reads**\n\n${reads.map(featureLine).join('')}\n`;
  }
  if (writes.length) {
    socketMd += `**Writes**\n\n${writes.map(featureLine).join('')}\n`;
  }
}

socketMd += `## Calling them

\`\`\`javascript
const client = new ServiceClient({
  transport: new SocketTransport({
    socket,          // the Roomful socket — required
    guru,            // the Valu Guru socket — for the ${onSocket.filter((d) => d.channel === 'valuguru').length} above
    applicationId,   // WHO is calling; the runtime stamps it
  }),
});

const ack = await client.call('Users.get', { userId });   // { data } | { error }
const user = await client.invoke('Users.get', { userId }); // throws on error
\`\`\`

Every one of them resolves an ack and never throws; the codes, the timeout and
the retry rules are [callbacks-policy.md](callbacks-policy.md). A function
resolves by any name the platform already writes — \`Users.get\`,
\`Users.get_user\`, \`Users.getUser\`, \`service__Users__get\`.
`;

// --- docs/api-pointers.md --------------------------------------------------
// The OTHER way over the postMessage bridge, written down. This package gives API
// pointers no catalogue and no per-function method, so the only description of
// the surface is the app's source — which is why the inventory is vendored in
// scripts/apiPointers.js and checked by `npm run measure:api-pointers`.
const pointers = pointerSummary();
const declaredKeys = new Set(descriptors.map((d) => d.key));
for (const f of API_POINTER_FUNCTIONS) {
  // A mapping to a function the catalogue does not declare is a typo, and a
  // typo here sends a reader to a function that does not exist.
  if (f.sdk && !declaredKeys.has(f.sdk)) {
    throw new Error(`api pointer ${f.module}.${f.fn} maps to unknown function ${f.sdk}`);
  }
  if (f.sdk && !f.via) throw new Error(`api pointer ${f.module}.${f.fn} names an SDK function but no 'via'`);
  if (!f.sdk && f.via) throw new Error(`api pointer ${f.module}.${f.fn} has a 'via' but no SDK function`);
}

const VIA_LABEL = {
  same: '✅ same',
  close: '⚠️ close',
};

let pointerMd = `<!-- GENERATED by scripts/generate.mjs from scripts/apiPointers.js. Do not edit: run \`npm run build\`. -->
# API pointers

The **older** way over the postMessage bridge, and the one this package
deliberately did not replace. An API pointer is a name and a version; you ask
the Valu Social application for one and then call functions on it by string:

\`\`\`javascript
const usersApi = await valuApi.getApi('users');   // → api:create-pointer
const me = await usersApi.run('current');         // → api:run
\`\`\`

There is **no per-function API** for any of this, here or anywhere: \`run\` takes
a string and an object, the application looks the string up in its own registry, and
nothing checks either side. That is the difference the service SDK makes — it
has a function per service because it *carries the implementations*, and a
pointer carries nothing but the string you passed.

What that costs, concretely:

- **No parameter validation.** A misspelled field is a successful call that
  answers nothing useful.
- **No consistent argument shape.** \`APIBridge.registerFunction\` refuses a
  function of more than one parameter, so every pointer function takes exactly
  one — but \`users.get\` takes a bare \`userId\` string while \`users.getIcon\`
  takes \`{userId, size}\`. There is no rule; you read the app's source.
- **No ack envelope.** A pointer call rejects with whatever the application threw.
  Declared functions all resolve \`{data} | {error}\`
  ([callbacks-policy.md](callbacks-policy.md)).
- **Frame only.** \`api:create-pointer\` is a postMessage message. A headless
  agent has no application to ask, so none of this exists outside an iframe.
- **No versioning discipline in practice.** Every function below is registered
  at version 1, and \`getApi(name)\` without a version binds the latest.
- **Events do not cross the bridge.** A pointer module on the application's side
  emits events (\`users\` emits \`update-user\` and
  \`update-user:following-status:\`), and \`APIPointer\` here has
  \`addEventListener\`. Nothing connects the two: the application sends no pointer
  events over the bridge (\`api:trigger\` carries \`on_route\` and nothing else),
  so a subscription from inside an iframe never fires. Those events are real only
  for callers inside the application itself.

## The inventory

${pointers.functions} functions across ${pointers.modules} modules, vendored in
[\`scripts/apiPointers.js\`](../scripts/apiPointers.js) and re-measured against a
real checkout by \`npm run measure:api-pointers\`, which exits non-zero the
moment the app adds, renames or drops one.

| | n |
|---|---|
| modules | ${pointers.modules} |
| functions | ${pointers.functions} |
| … a declared SDK function does the same work | ${pointers.same} |
| … a declared function is close but not equivalent | ${pointers.close} |
| … **no declared intent: the pointer is the only way** | ${pointers.only} |

So two thirds of this surface is not reachable through the service SDK at all,
and that is the answer to "what still relies on API pointers": theming and
resize, network switching, the modal stack, logout, chat-channel resolution,
removing a connection, the encryption seed, and the dock's loading and
link-blocking overrides.

The \`✅ same\` rows are the ones to stop using first — a declared function
covers them, with validation, caching and one failure shape, and it works
headless as well as framed.

`;

for (const m of API_POINTER_MODULES) {
  pointerMd += `### ${m.module}${m.aliases.length ? ` (also ${m.aliases.map((a) => `\`${a}\``).join(', ')})` : ''}\n\n`;
  pointerMd += `${m.summary}\n\n`;
  pointerMd += `\`getApi('${m.module}')\`${m.aliases.length ? ` — or ${m.aliases.map((a) => `\`getApi('${a}')\``).join(', ')}` : ''}`
    + ` → [\`${m.file}\`](https://github.com/Roomful/valusocial-web/blob/develop/${m.file})\n\n`;
  pointerMd += `| \`run(…)\` | its one argument | what it does | declared equivalent |\n|---|---|---|---|\n`;
  for (const f of m.functions) {
    const equivalent = f.sdk ? `${VIA_LABEL[f.via]} \`${f.sdk}\`` : '— none';
    pointerMd += `| \`${f.fn}\` | \`${f.arg}\` | ${f.does} | ${equivalent} |\n`;
  }
  pointerMd += `\n`;
  const noted = m.functions.filter((f) => f.note);
  if (noted.length) {
    for (const f of noted) pointerMd += `- \`${f.fn}\` — ${f.note}\n`;
    pointerMd += `\n`;
  }
}

// Two modules claiming one name is not hypothetical here, and it resolves
// differently for a module name than for an alias — which is the kind of thing
// a reader told "call getApi('chat')" needs to know.
const aliasOwners = new Map();
for (const m of API_POINTER_MODULES) {
  for (const a of m.aliases) {
    if (!aliasOwners.has(a)) aliasOwners.set(a, []);
    aliasOwners.get(a).push(m.module);
  }
}
const collidingAliases = [...aliasOwners].filter(([, owners]) => owners.length > 1);

pointerMd += `## Names that collide

\`${DUPLICATE_DECLARATIONS.map((d) => d.module).join('`, `')}\` is declared **twice**: once above, and again by
${DUPLICATE_DECLARATIONS.map((d) => `[\`${d.file}\`](https://github.com/Roomful/valusocial-web/blob/develop/${d.file}) with the same `
  + `${d.functions.length} functions (${d.functions.map((f) => `\`${f}\``).join(', ')})`).join(', ')}.
\`APIBridge.createAPi\` throws on a duplicate module name, so at most one of the
two is ever live; the tables above count the pair once. ${pointers.declarations} registrations,
${pointers.functions} distinct functions.

An **alias** collides silently instead — \`registerAlias\` just overwrites the
entry, so the last module to register the name owns it:
${collidingAliases.map(([a, owners]) => `\`${a}\` is registered by both \`${owners.join('` and `')}\``).join('; ')}.
Prefer the module's own name over an alias for exactly this reason.

## What this package does and does not do about them

- \`ValuApi.getApi()\` and \`APIPointer\` are **unchanged**. Phase 1 moved the
  transport out from under them — the wire messages are byte for byte what they
  were — and Phase 2 did not touch them.
- One behaviour did change, because it was broken: \`sendIntent\` never settled,
  because its \`api:run-completed\` reply was routed as if it belonged to an
  \`APIPointer\`. It resolves now.
- **Nothing in the service SDK uses a pointer.** \`ServiceClient\` and
  \`FrameCommands\` both send \`api:service-intent\`.
- There is no plan in Phases 1–2 to wrap them. A pointer function that deserves
  to be callable from an agent should be **declared as an intent** and
  implemented here; the ${pointers.only} above are the candidate list.

"Over the bridge" in all of this means the same postMessage channel every other
doc here means — [postmessage-vs-socket.md](postmessage-vs-socket.md).
`;

// --- write or check --------------------------------------------------------
const outputs = [
  ['src/services/catalog.generated.js', catalogJs],
  ['types/valu-services.d.ts', dts],
  ['docs/services.md', md],
  ['docs/server-functions.md', serverMd],
  ['docs/socket-functions.md', socketMd],
  ['docs/api-pointers.md', pointerMd],
  ['docs/parity.md', parity],
  ['docs/parity-matrix.csv', csv],
];

let stale = 0;
for (const [path, content] of outputs) {
  const url = new URL(path, root);
  if (check) {
    let current = '';
    try { current = readFileSync(url, 'utf8'); } catch { /* missing counts as stale */ }
    if (current !== content) {
      console.error(`STALE: ${path} — run \`npm run build\``);
      stale++;
    }
  } else {
    writeFileSync(url, content, 'utf8');
    console.log(`wrote ${path}`);
  }
}

if (check && stale) process.exit(1);
if (check) console.log(`generated output is up to date (${outputs.length} files)`);
if (!check) {
  console.log(
    `${descriptors.length} descriptors: ${counts.socket} socket, ${counts.local} local, ${counts.postmessage} postmessage`,
  );
}
