// ===========================================================================
// Generate the service catalogue from the manifest snapshot.
//
//   node scripts/generate.mjs           # write
//   node scripts/generate.mjs --check   # fail if the committed output differs
//
// One descriptor per declared function. Everything downstream — the runtime
// validator, the TypeScript types, the docs, the LLM tool definitions — is
// derived from these descriptors, so the manifest stops being documentation
// and becomes the thing that decides whether a call is allowed.
// ===========================================================================
import { readFileSync, writeFileSync } from 'node:fs';
import {
  HOST_BOUND, LOCAL, SERVER_TOOLS, SERVER_ONLY_TOOLS, mutates, defaultCache,
} from './bindings.js';

const root = new URL('../', import.meta.url);
const check = process.argv.includes('--check');

const snapshot = JSON.parse(
  readFileSync(new URL('manifests/service-manifests.snapshot.json', root), 'utf8'),
);

const hostBound = new Set(HOST_BOUND);
const local = new Set(LOCAL);
const serverTools = new Set(SERVER_TOOLS);

const snake = (action) => action.replace(/-/g, '_');
const camel = (action) => action.replace(/[-_](\w)/g, (_, c) => c.toUpperCase());

const descriptors = [];
for (const service of snapshot.services) {
  for (const intent of service.intents) {
    const key = `${service.id}.${intent.action}`;
    const binding = hostBound.has(key) ? 'host' : local.has(key) ? 'local' : 'socket';
    const isMutation = mutates(key, intent.action);
    descriptors.push({
      key,
      service: service.id,
      action: intent.action,
      fn: snake(intent.action),
      method: camel(intent.action),
      toolName: `service__${service.id}__${snake(intent.action)}`,
      serviceTitle: service.title,
      serviceDescription: service.description,
      source: service.source,
      description: intent.description,
      availability: intent.availability,
      permissions: intent.permissions,
      // No manifest intent declares permissions today, so the scope a caller
      // needs is derived: one read scope and one write scope per service.
      scopes: [`${service.id.toLowerCase()}:${isMutation ? 'write' : 'read'}`],
      binding,
      mutates: isMutation,
      cache: defaultCache(key, binding, isMutation, intent.params),
      // Filled in per function during Phase 2 (definition of done: "descriptor").
      returns: { type: 'unknown', description: '' },
      params: intent.params,
      implementedBy: serverTools.has(key) ? `service__${service.id}__${snake(intent.action)}` : null,
    });
  }
}

descriptors.sort((a, b) => a.key.localeCompare(b.key));

// --- src/services/catalog.generated.js -------------------------------------
const banner = `// GENERATED by scripts/generate.mjs from manifests/service-manifests.snapshot.json.
// Do not edit by hand: run \`npm run build\`. The decisions that are not in the
// manifest (socket/local/host, mutates, cache) come from scripts/bindings.js.
`;

const catalogJs = `${banner}
/** @typedef {import('./descriptors.js').ServiceDescriptor} ServiceDescriptor */

/** @type {ServiceDescriptor[]} */
export const SERVICE_DESCRIPTORS = ${JSON.stringify(descriptors, null, 2)};

/** Server tools that implement no declared intent — Phase 2b decides their fate. */
export const SERVER_ONLY_TOOLS = ${JSON.stringify(SERVER_ONLY_TOOLS, null, 2)};
`;

// --- types/valu-services.d.ts ----------------------------------------------
const tsType = (type) => ({
  string: 'string', number: 'number', boolean: 'boolean', object: 'Record<string, any>',
  array: 'any[]', 'string[]': 'string[]', 'object[]': 'Record<string, any>[]',
  FileList: 'FileList',
}[type] ?? 'any');

const paramType = (param) =>
  param.options ? param.options.map((o) => JSON.stringify(o)).join(' | ') : tsType(param.type);

const jsdoc = (indent, lines) =>
  `${indent}/**\n${lines.filter(Boolean).map((l) => `${indent} * ${l}`).join('\n')}\n${indent} */`;

const byService = new Map();
for (const d of descriptors) {
  if (!byService.has(d.service)) byService.set(d.service, []);
  byService.get(d.service).push(d);
}

let dts = `${banner}
// Typed surface of every declared Valu service function.

import type { ValuAck } from './valu-api';

export type ServiceBinding = 'socket' | 'local' | 'host';
export type IntentAvailability = 'ai' | 'developer';

`;

for (const [service, fns] of byService) {
  for (const d of fns) {
    const all = [...d.params.required.map((p) => [p, true]), ...d.params.optional.map((p) => [p, false])];
    dts += `${jsdoc('', [`${d.key} — ${d.description}`])}\n`;
    dts += `export interface ${service}${d.method[0].toUpperCase()}${d.method.slice(1)}Params {\n`;
    for (const [p, required] of all) {
      dts += `${jsdoc('  ', [p.description])}\n`;
      dts += `  ${p.name}${required ? '' : '?'}: ${paramType(p)};\n`;
    }
    dts += `}\n\n`;
  }
}

dts += `/** Every service, with each declared function as a method. */\nexport interface ValuServices {\n`;
for (const [service, fns] of byService) {
  dts += `${jsdoc('  ', [fns[0].serviceDescription])}\n  ${service}: {\n`;
  for (const d of fns) {
    const hasParams = d.params.required.length + d.params.optional.length > 0;
    const required = d.params.required.length > 0;
    const paramsName = `${service}${d.method[0].toUpperCase()}${d.method.slice(1)}Params`;
    dts += `${jsdoc('    ', [d.description, `@binding ${d.binding}`, `@scope ${d.scopes.join(' ')}`])}\n`;
    dts += `    ${d.method}(${hasParams ? `params${required ? '' : '?'}: ${paramsName}` : ''}): Promise<ValuAck>;\n`;
  }
  dts += `  };\n`;
}
dts += `}\n\nexport type ServiceName = keyof ValuServices;\n`;

// --- docs/services.md ------------------------------------------------------
const counts = descriptors.reduce((acc, d) => ({ ...acc, [d.binding]: (acc[d.binding] ?? 0) + 1 }), {});
let md = `<!-- GENERATED by scripts/generate.mjs. Do not edit: run \`npm run build\`. -->
# Valu service reference

Every function the app declares in \`SERVICE_MANIFESTS\`, with the binding that
serves it and the scope a caller needs.

| binding | count | meaning |
|---|---|---|
| \`socket\` | ${counts.socket} | answered over the Valu socket |
| \`local\` | ${counts.local} | answered by the SDK itself |
| \`host\` | ${counts.host} | host/UI-bound — stays on the postMessage bridge |
| **total** | **${descriptors.length}** | |

${SERVER_ONLY_TOOLS.length} server tools implement no declared intent and are not in this
table: ${SERVER_ONLY_TOOLS.map((t) => `\`${t}\``).join(', ')}.

`;

for (const [service, fns] of byService) {
  md += `## ${service}\n\n${fns[0].serviceDescription}\n\nSource: \`${fns[0].source}\`\n\n`;
  for (const d of fns) {
    md += `### \`${d.key}\`\n\n${d.description}\n\n`;
    md += `- binding: \`${d.binding}\`${d.implementedBy ? ` · server tool: \`${d.implementedBy}\`` : ''}\n`;
    md += `- scope: \`${d.scopes.join('`, `')}\` · ${d.mutates ? 'mutates state' : 'read-only'}\n`;
    md += `- cache: \`${d.cache.mode}\`${d.cache.mode !== 'none' ? ` (ttl ${d.cache.ttlMs}ms, key \`${d.cache.key ?? 'service'}\`)` : ''}\n`;
    md += `- availability: ${d.availability.length ? d.availability.map((a) => `\`${a}\``).join(', ') : '_none_'}\n\n`;
    const all = [...d.params.required.map((p) => [p, true]), ...d.params.optional.map((p) => [p, false])];
    if (all.length) {
      md += `| param | type | required | description |\n|---|---|---|---|\n`;
      for (const [p, required] of all) {
        const type = p.options ? p.options.map((o) => `\`${o}\``).join(' \\| ') : `\`${p.type}\``;
        md += `| \`${p.name}\` | ${type} | ${required ? 'yes' : 'no'} | ${p.description.replace(/\|/g, '\\|')} |\n`;
      }
      md += `\n`;
    } else {
      md += `Takes no parameters.\n\n`;
    }
  }
}

// --- write or check --------------------------------------------------------
const outputs = [
  ['src/services/catalog.generated.js', catalogJs],
  ['types/valu-services.d.ts', dts],
  ['docs/services.md', md],
];

let stale = 0;
for (const [path, content] of outputs) {
  const url = new URL(path, root);
  if (check) {
    let current = '';
    try { current = readFileSync(url, 'utf8'); } catch { /* missing counts as stale */ }
    if (current !== content) {
      console.error(`STALE: ${path} — run \`npm run build\``);
      stale++;
    }
  } else {
    writeFileSync(url, content, 'utf8');
    console.log(`wrote ${path}`);
  }
}

if (check && stale) process.exit(1);
if (check) console.log(`generated output is up to date (${outputs.length} files)`);
if (!check) {
  console.log(
    `${descriptors.length} descriptors: ${counts.socket} socket, ${counts.local} local, ${counts.host} host`,
  );
}
