// ===========================================================================
// Generate the service catalogue from the manifest snapshot.
//
//   node scripts/generate.mjs           # write
//   node scripts/generate.mjs --check   # fail if the committed output differs
//
// One descriptor per declared function. Everything downstream — the runtime
// validator, the TypeScript types, the docs, the LLM tool definitions — is
// derived from these descriptors, so the manifest stops being documentation
// and becomes the thing that decides whether a call is allowed.
// ===========================================================================
import { readFileSync, writeFileSync } from 'node:fs';
import {
  HOST_BOUND, LOCAL, SERVER_TOOLS, SERVER_ONLY_TOOLS, mutates, defaultCache,
} from './bindings.js';
import {
  VALUGURU_CHANNEL, HOST_STATE_CHANNEL, RETURNS, SERVER_ONLY_RECONCILIATION, KNOWN_DELTAS,
  REQUIREMENTS,
} from './functions.js';
// The registry the SDK actually loads. Importing it is what lets the parity
// matrix report implementation status instead of asserting it.
import { serviceRegistry } from '../src/services/registry.js';
import '../src/services/impl/index.js';

const root = new URL('../', import.meta.url);
const check = process.argv.includes('--check');

const snapshot = JSON.parse(
  readFileSync(new URL('manifests/service-manifests.snapshot.json', root), 'utf8'),
);

const hostBound = new Set(HOST_BOUND);
const local = new Set(LOCAL);
const serverTools = new Set(SERVER_TOOLS);
const valuguru = new Set(VALUGURU_CHANNEL);
const hostState = new Set(HOST_STATE_CHANNEL);

/**
 * WHICH socket (or none) serves a declared function. `binding` says the kind
 * of thing that answers; `channel` says the thing itself — the distinction
 * Phase 2 had to make before a handler could be written (scripts/functions.js).
 */
function channelFor(key, binding) {
  if (binding !== 'socket') return binding;
  if (valuguru.has(key)) return 'valuguru';
  if (hostState.has(key)) return 'host-state';
  return 'roomful';
}

const snake = (action) => action.replace(/-/g, '_');
const camel = (action) => action.replace(/[-_](\w)/g, (_, c) => c.toUpperCase());

const descriptors = [];
for (const service of snapshot.services) {
  for (const intent of service.intents) {
    const key = `${service.id}.${intent.action}`;
    const binding = hostBound.has(key) ? 'host' : local.has(key) ? 'local' : 'socket';
    const channel = channelFor(key, binding);
    const isMutation = mutates(key, intent.action);
    descriptors.push({
      key,
      service: service.id,
      action: intent.action,
      fn: snake(intent.action),
      method: camel(intent.action),
      toolName: `service__${service.id}__${snake(intent.action)}`,
      serviceTitle: service.title,
      serviceDescription: service.description,
      source: service.source,
      description: intent.description,
      availability: intent.availability,
      permissions: intent.permissions,
      // No manifest intent declares permissions today, so the scope a caller
      // needs is derived: one read scope and one write scope per service.
      scopes: [`${service.id.toLowerCase()}:${isMutation ? 'write' : 'read'}`],
      binding,
      mutates: isMutation,
      cache: defaultCache(key, binding, isMutation, intent.params, channel),
      channel,
      returns: RETURNS[key] ?? { type: 'unknown', description: '' },
      params: intent.params,
      implementedBy: serverTools.has(key) ? `service__${service.id}__${snake(intent.action)}` : null,
    });
  }
}

descriptors.sort((a, b) => a.key.localeCompare(b.key));

// --- src/services/catalog.generated.js -------------------------------------
const banner = `// GENERATED by scripts/generate.mjs from manifests/service-manifests.snapshot.json.
// Do not edit by hand: run \`npm run build\`. The decisions that are not in the
// manifest (socket/local/host, mutates, cache) come from scripts/bindings.js.
`;

const catalogJs = `${banner}
/** @typedef {import('./descriptors.js').ServiceDescriptor} ServiceDescriptor */

/** @type {ServiceDescriptor[]} */
export const SERVICE_DESCRIPTORS = ${JSON.stringify(descriptors, null, 2)};

/** Server tools that implement no declared intent. */
export const SERVER_ONLY_TOOLS = ${JSON.stringify(SERVER_ONLY_TOOLS, null, 2)};

/** Phase 2b — what happens to each of them, and why (scripts/functions.js). */
export const SERVER_ONLY_RECONCILIATION = ${JSON.stringify(SERVER_ONLY_RECONCILIATION, null, 2)};
`;

// --- types/valu-services.d.ts ----------------------------------------------
const tsType = (type) => ({
  string: 'string', number: 'number', boolean: 'boolean', object: 'Record<string, any>',
  array: 'any[]', 'string[]': 'string[]', 'object[]': 'Record<string, any>[]',
  FileList: 'FileList',
}[type] ?? 'any');

const paramType = (param) =>
  param.options ? param.options.map((o) => JSON.stringify(o)).join(' | ') : tsType(param.type);

const jsdoc = (indent, lines) =>
  `${indent}/**\n${lines.filter(Boolean).map((l) => `${indent} * ${l}`).join('\n')}\n${indent} */`;

const byService = new Map();
for (const d of descriptors) {
  if (!byService.has(d.service)) byService.set(d.service, []);
  byService.get(d.service).push(d);
}

let dts = `${banner}
// Typed surface of every declared Valu service function.

// The package's hand-written declarations are an AMBIENT module, so this
// names the package rather than the file: both are in the same program
// (\`npm run typecheck\`), and a relative import of an ambient module does not
// resolve.
import type { ValuAck } from '@arkeytyp/valu-api';

export type ServiceBinding = 'socket' | 'local' | 'host';
export type IntentAvailability = 'ai' | 'developer';

`;

/** The declared return shape, as TypeScript. `object` is an open record. */
const returnType = (returns) => (returns?.type && returns.type !== 'unknown'
  ? returns.type.replace(/\bobject\b/g, 'Record<string, any>')
  : 'any');

const resultName = (d) => `${d.service}${d.method[0].toUpperCase()}${d.method.slice(1)}Result`;

for (const [service, fns] of byService) {
  for (const d of fns) {
    const all = [...d.params.required.map((p) => [p, true]), ...d.params.optional.map((p) => [p, false])];
    dts += `${jsdoc('', [`${d.key} — ${d.returns.description || d.description}`])}\n`;
    dts += `export type ${resultName(d)} = ${returnType(d.returns)};\n\n`;
    dts += `${jsdoc('', [`${d.key} — ${d.description}`])}\n`;
    dts += `export interface ${service}${d.method[0].toUpperCase()}${d.method.slice(1)}Params {\n`;
    for (const [p, required] of all) {
      dts += `${jsdoc('  ', [p.description])}\n`;
      dts += `  ${p.name}${required ? '' : '?'}: ${paramType(p)};\n`;
    }
    dts += `}\n\n`;
  }
}

dts += `/** Every service, with each declared function as a method. */\nexport interface ValuServices {\n`;
for (const [service, fns] of byService) {
  dts += `${jsdoc('  ', [fns[0].serviceDescription])}\n  ${service}: {\n`;
  for (const d of fns) {
    const hasParams = d.params.required.length + d.params.optional.length > 0;
    const required = d.params.required.length > 0;
    const paramsName = `${service}${d.method[0].toUpperCase()}${d.method.slice(1)}Params`;
    dts += `${jsdoc('    ', [d.description, `@binding ${d.binding}`, `@channel ${d.channel}`, `@scope ${d.scopes.join(' ')}`])}\n`;
    dts += `    ${d.method}(${hasParams ? `params${required ? '' : '?'}: ${paramsName}` : ''}): Promise<ValuAck<${resultName(d)}>>;\n`;
  }
  dts += `  };\n`;
}
dts += `}\n\nexport type ServiceName = keyof ValuServices;\n`;

// --- docs/services.md ------------------------------------------------------
const counts = descriptors.reduce((acc, d) => ({ ...acc, [d.binding]: (acc[d.binding] ?? 0) + 1 }), {});
let md = `<!-- GENERATED by scripts/generate.mjs. Do not edit: run \`npm run build\`. -->
# Valu service reference

Every function the app declares in \`SERVICE_MANIFESTS\`, with the binding that
serves it and the scope a caller needs.

| binding | count | meaning |
|---|---|---|
| \`socket\` | ${counts.socket} | answered over the Valu socket |
| \`local\` | ${counts.local} | answered by the SDK itself |
| \`host\` | ${counts.host} | host/UI-bound — stays on the postMessage bridge |
| **total** | **${descriptors.length}** | |

${SERVER_ONLY_TOOLS.length} server tools implement no declared intent and are not in this
table: ${SERVER_ONLY_TOOLS.map((t) => `\`${t}\``).join(', ')}.

`;

for (const [service, fns] of byService) {
  md += `## ${service}\n\n${fns[0].serviceDescription}\n\nSource: \`${fns[0].source}\`\n\n`;
  for (const d of fns) {
    md += `### \`${d.key}\`\n\n${d.description}\n\n`;
    md += `- binding: \`${d.binding}\` · channel: \`${d.channel}\`${d.implementedBy ? ` · server tool: \`${d.implementedBy}\`` : ''}\n`;
    md += `- returns: \`${d.returns.type}\`${d.returns.description ? ` — ${d.returns.description}` : ''}\n`;
    md += `- scope: \`${d.scopes.join('`, `')}\` · ${d.mutates ? 'mutates state' : 'read-only'}\n`;
    md += `- cache: \`${d.cache.mode}\`${d.cache.mode !== 'none' ? ` (ttl ${d.cache.ttlMs}ms, key \`${d.cache.key ?? 'service'}\`)` : ''}\n`;
    md += `- availability: ${d.availability.length ? d.availability.map((a) => `\`${a}\``).join(', ') : '_none_'}\n\n`;
    const all = [...d.params.required.map((p) => [p, true]), ...d.params.optional.map((p) => [p, false])];
    if (all.length) {
      md += `| param | type | required | description |\n|---|---|---|---|\n`;
      for (const [p, required] of all) {
        const type = p.options ? p.options.map((o) => `\`${o}\``).join(' \\| ') : `\`${p.type}\``;
        md += `| \`${p.name}\` | ${type} | ${required ? 'yes' : 'no'} | ${p.description.replace(/\|/g, '\\|')} |\n`;
      }
      md += `\n`;
    } else {
      md += `Takes no parameters.\n\n`;
    }
  }
}

// --- docs/parity.md + docs/parity-matrix.csv --------------------------------
// THE PARITY MATRIX, generated rather than maintained. The plan shipped it as
// a spreadsheet; a spreadsheet cannot notice that a function was implemented,
// so this is built from the catalogue AND from the registry — `npm run
// check:generated` fails when the two drift, which is the only way a parity
// table stays true after the week it was written.
const implemented = new Set(serviceRegistry.implemented());

const STATUS = (d) => {
  if (d.binding === 'host') return 'frame command';
  return implemented.has(d.key) ? 'implemented' : 'declared only';
};

const byChannel = descriptors.reduce((acc, d) => ({ ...acc, [d.channel]: (acc[d.channel] ?? 0) + 1 }), {});
const implementedCount = descriptors.filter((d) => implemented.has(d.key)).length;

let parity = `<!-- GENERATED by scripts/generate.mjs. Do not edit: run \`npm run build\`. -->
# Parity matrix

Every declared function, what serves it, and whether this package implements
it. Generated from the catalogue and from the registry the SDK actually loads,
so a function listed \`implemented\` here has a handler — the two cannot drift
without \`npm run check:generated\` failing.

| | count |
|---|---|
| declared service intents | **${descriptors.length}** |
| SDK-able (socket + local) | **${descriptors.length - counts.host}** |
| implemented in this package | **${implementedCount}** |
| frame commands (host-bound) | **${counts.host}** |
| server tools with no declared intent | **${SERVER_ONLY_TOOLS.length}** |

## Channels

\`binding\` says the KIND of thing that answers; \`channel\` says which one.
Phase 2 added the second column: "socket" turned out to be three different
things, and a function written for the wrong one fails in a way the ack
envelope cannot explain.

| channel | count | what serves it |
|---|---|---|
| \`roomful\` | ${byChannel.roomful ?? 0} | the Roomful platform socket — \`ValuSocket.emit(ns, payload)\` |
| \`valuguru\` | ${byChannel.valuguru ?? 0} | the Valu Guru server's \`data_request\` channel — \`valuguru.*\` ops |
| \`host-state\` | ${byChannel['host-state'] ?? 0} | no RPC exists; the answer is in the host's memory |
| \`local\` | ${byChannel.local ?? 0} | computed by the SDK |
| \`host\` | ${byChannel.host ?? 0} | the frame bridge (\`src/frame/FrameCommands.js\`) |

## Functions

| service | function | binding | channel | mutates | cache | server tool | status |
|---|---|---|---|---|---|---|---|
`;
for (const d of descriptors) {
  parity += `| ${d.service} | \`${d.action}\` | ${d.binding} | \`${d.channel}\` | ${d.mutates ? 'write' : 'read'} `
    + `| \`${d.cache.mode}\` | ${d.implementedBy ? `\`${d.implementedBy}\`` : '—'} | ${STATUS(d)} |\n`;
}

parity += `
## Server-only tools — the Phase 2b decisions

${SERVER_ONLY_TOOLS.length} tools in valu-guru-server implement no declared intent. Each one is
resolved below rather than left as a gap.

`;
for (const entry of SERVER_ONLY_RECONCILIATION) {
  parity += `### \`${entry.tool}\` — ${entry.disposition}\n\n${entry.decision}\n\n`;
  if (entry.declared.length) {
    parity += `Declared equivalent: ${entry.declared.map((k) => `\`${k}\``).join(', ')}.\n\n`;
  }
}

parity += `## Known behaviour deltas

Parity is not identical behaviour. These are the places this package knowingly
differs from the app, each one a decision rather than an oversight.

`;
for (const entry of KNOWN_DELTAS) {
  parity += `### \`${entry.key}\`\n\n${entry.delta}\n\n`;
}

// The same table as data, for anything that would rather diff than read.
let csv = 'service,function,binding,channel,mutates,cache,scopes,server_tool,status,returns\n';
for (const d of descriptors) {
  const cell = (v) => `"${String(v).replace(/"/g, '""')}"`;
  csv += [
    d.service, d.action, d.binding, d.channel, d.mutates ? 'write' : 'read', d.cache.mode,
    d.scopes.join(' '), d.implementedBy ?? '', STATUS(d), d.returns.type,
  ].map(cell).join(',') + '\n';
}

// --- docs/server-functions.md ----------------------------------------------
// THE SERVER-SIDE REFERENCE: what this package answers itself, for somebody
// wiring it into a runtime that is not a browser frame. docs/services.md lists
// what the platform DECLARES; this lists what the package SERVES, and what the
// runtime has to hand it before a call can succeed.
const served = descriptors.filter((d) => d.binding !== 'host' && implemented.has(d.key));
const frame = descriptors.filter((d) => d.binding === 'host');
const servedByService = new Map();
for (const d of served) {
  if (!servedByService.has(d.service)) servedByService.set(d.service, []);
  servedByService.get(d.service).push(d);
}

/**
 * Frame command → the method that runs it, read out of FrameCommands itself.
 *
 * NOT derived from the action name: five of the fifteen are deliberately named
 * for what they do rather than what the intent is called (`AiGuru.open` is
 * `openApplication`, `Application.close-application` is `closeSelf`), and a
 * table that camel-cased the action would send a reader to a method that does
 * not exist.
 */
const frameMethods = (() => {
  const src = readFileSync(new URL('src/frame/FrameCommands.js', root), 'utf8');
  const methods = new Map();
  let current = null;
  for (const line of src.split('\n')) {
    const declaration = /^\s{2}([a-zA-Z][\w]*)\s*\(/.exec(line);
    if (declaration) current = declaration[1];
    const run = /this\.run\('([^']+)'/.exec(line);
    if (run && current) methods.set(run[1], current);
  }
  return methods;
})();

for (const d of frame) {
  if (!frameMethods.has(d.key)) {
    throw new Error(`${d.key} is host-bound but no FrameCommands method runs it`);
  }
}

/** The runtime requirements of a function: its channel, plus anything extra. */
const requirementsOf = (d) => {
  const channelReq = {
    roomful: '`socket`',
    valuguru: '`guru`',
    'host-state': null,
    local: null,
  }[d.channel];
  const extra = (REQUIREMENTS[d.key] ?? []).map((r) => `\`${r}\``);
  return [channelReq, ...extra].filter(Boolean).join(', ') || '—';
};

const signature = (d) => {
  const all = [
    ...d.params.required.map((p) => p.name),
    ...d.params.optional.map((p) => `${p.name}?`),
  ];
  return all.length ? `{${all.join(', ')}}` : '—';
};

const channelCounts = served.reduce((acc, d) => ({ ...acc, [d.channel]: (acc[d.channel] ?? 0) + 1 }), {});

let serverMd = `<!-- GENERATED by scripts/generate.mjs. Do not edit: run \`npm run build\`. -->
# Server functions

The ${served.length} functions **this package answers itself** — over a socket, or
locally — and what a runtime has to give it before each one can succeed.

This is the reference for embedding the SDK in something that is not a browser
frame: a Node service, an agent runtime, a test harness. For the platform's own
declaration of every intent (including the ${frame.length} that only a frame can serve)
read [services.md](services.md); for who implements what today read
[parity.md](parity.md).

Generated from the catalogue and from the registry the SDK actually loads: a
function listed here has a handler, and its requirements are asserted against
that handler by \`test/server-functions.test.js\`.

## Calling one

\`\`\`javascript
import { ServiceClient } from '@arkeytyp/valu-api/src/services/ServiceClient.js';
import { SocketTransport } from '@arkeytyp/valu-api/src/transport/SocketTransport.js';
import { NodeSocketAdapter } from '@arkeytyp/valu-api/src/socket/NodeSocketAdapter.js';

const client = new ServiceClient({
  transport: new SocketTransport({
    socket: new NodeSocketAdapter({ connection }), // the Roomful socket
    guru,                                          // the Valu Guru socket
    host,                                          // state only the host holds
    applicationId: 'my-app',                       // WHO is calling
    config: { webBase, apiGate },                  // origins for URL builders
    fetchImpl: fetch,
  }),
});

const ack = await client.call('Users.get', { userId });   // { data } | { error }
const user = await client.invoke('Users.get', { userId }); // throws on error
\`\`\`

A function resolves by any name the platform already writes — \`Users.get\`,
\`Users.get_user\`, \`Users.getUser\`, \`service__Users__get\`.

## What a runtime must supply

| requirement | what it is | what happens without it |
|---|---|---|
| \`socket\` | a [\`ValuSocket\`](../src/socket/ValuSocket.js) — \`NodeSocketAdapter\` over a \`RoomfulConnectionManager\`, or \`BrowserSocketAdapter\` over the app's WebSocket service | \`SocketTransport\` refuses to construct |
| \`guru\` | a [\`ValuGuruSocket\`](../src/socket/ValuGuruSocket.js) — the Valu Guru server's \`data_request\` channel | the ${channelCounts.valuguru ?? 0} \`valuguru\` functions answer 503 **by name**, before the handler runs |
| \`host\` | a [\`HostState\`](../src/host/HostState.js): state no RPC can produce | the function answers 501 naming the capability it wanted |
| \`applicationId\` | WHICH application is calling, stamped by the host and never read from a caller's params | the functions scoped to an app answer 403 |
| \`config\` | \`{ webBase, apiGate }\` — the origins a resource URL is built on | defaults are used; a share link may point at the wrong deployment |
| \`fetch\` | outbound HTTP, for the local HTTP functions and the upload pipeline's bucket PUT | \`globalThis.fetch\`, if the runtime has one |

By channel: ${Object.entries(channelCounts).sort().map(([c, n]) => `${n} \`${c}\``).join(' · ')}.

## Errors

Every function resolves an ack — \`{data}\` or \`{error}\` — and never throws;
\`invoke\` is the throwing wrapper. The codes a caller must handle are in
[callbacks-policy.md](callbacks-policy.md); the ones specific to a missing
runtime piece are 503 (no such channel), 501 (no host capability, or a function
the transport cannot serve) and 403 (no application identity).

`;

for (const [service, fns] of servedByService) {
  serverMd += `## ${service}\n\n${fns[0].serviceDescription}\n\n`;
  serverMd += `| function | params | returns | mode | requires | cache |\n|---|---|---|---|---|---|\n`;
  for (const d of fns) {
    serverMd += `| \`${d.key}\` | ${signature(d)} | \`${d.returns.type}\` `
      + `| ${d.mutates ? 'write' : 'read'} | ${requirementsOf(d)} | \`${d.cache.mode}\` |\n`;
  }
  serverMd += `\n`;
  for (const d of fns) {
    // A `void` function's declared return reads as a statement of fact ("The
    // resource was deleted."); everything else names a value, so it reads as
    // the answer to the call.
    const answers = !d.returns.description ? ''
      : d.returns.type === 'void' ? ` ${d.returns.description}`
        : ` Answers ${d.returns.description.charAt(0).toLowerCase()}${d.returns.description.slice(1)}`;
    serverMd += `- \`${d.action}\` — ${d.description}${answers}\n`;
  }
  serverMd += `\n`;
}

serverMd += `## Not served here

${frame.length} declared intents are host/UI-bound: a picker that renders, a dock that
opens, a log buffer only the frame holds. A socket answers all ${frame.length} with the
same 501, and [\`src/frame/FrameCommands.js\`](../src/frame/FrameCommands.js)
gives them a named API over the postMessage bridge instead.

| intent | frame method |
|---|---|
`;
for (const d of frame) {
  serverMd += `| \`${d.key}\` | \`frame.${frameMethods.get(d.key)}()\` |\n`;
}

serverMd += `
${SERVER_ONLY_TOOLS.length} tools in valu-guru-server implement no declared intent and are not
functions of this package. [parity.md](parity.md) records the decision for each
one: ${SERVER_ONLY_TOOLS.map((t) => `\`${t}\``).join(', ')}.
`;

// --- write or check --------------------------------------------------------
const outputs = [
  ['src/services/catalog.generated.js', catalogJs],
  ['types/valu-services.d.ts', dts],
  ['docs/services.md', md],
  ['docs/server-functions.md', serverMd],
  ['docs/parity.md', parity],
  ['docs/parity-matrix.csv', csv],
];

let stale = 0;
for (const [path, content] of outputs) {
  const url = new URL(path, root);
  if (check) {
    let current = '';
    try { current = readFileSync(url, 'utf8'); } catch { /* missing counts as stale */ }
    if (current !== content) {
      console.error(`STALE: ${path} — run \`npm run build\``);
      stale++;
    }
  } else {
    writeFileSync(url, content, 'utf8');
    console.log(`wrote ${path}`);
  }
}

if (check && stale) process.exit(1);
if (check) console.log(`generated output is up to date (${outputs.length} files)`);
if (!check) {
  console.log(
    `${descriptors.length} descriptors: ${counts.socket} socket, ${counts.local} local, ${counts.host} host`,
  );
}
